def REGISTRY = ''
pipeline {
    agent {
	}

	options {

	}

    stages {
        stage('build') {
            steps {
            }
        }
        stage("push") {
            steps {
                script {
                    }
                }
            }
        }
    }
}